### PR TITLE
Check it out, more response messages!

### PR DESCRIPTION
**Pull request by rafaelcn**
Ready to go @luizperes!

### CODE REVIEW

**Comment by rafaelcn** [comment]
I'd merge right away if I were you :see_no_evil:

**Comment by luizperes** [comment]
you will need to switch the `if`s with `elif`s later :P

**Comment by rafaelcn** [comment]
nha, gonna do it now

**Comment by rafaelcn** [comment]
But it actually would work out in the same way, wouldn't it? Although a little bit slower of course.

**Comment by luizperes** [comment]
in theory a sentence could have both of them, so that would be fine.. but otherwise it would branch in all `if`s

**Comment by rafaelcn** [comment]
Exactly!

**Pull request merged**
